import testPerfume from "../assets/images/perfumes/parfum.webp";

export const perfumes = [
  {
    id: "1001827364",
    image: testPerfume,
    name: "Meadow Bliss",
    flavour: "Breezy & Joyful",
    price: "35000",
    description:
      "A light, airy fragrance evoking sun-drenched fields and carefree joy.",
    inStock: true,
    category: "Floral",
    size: "100ml",
    notes: {
      top: "Green Apple, Bergamot",
      heart: "Peony, Freesia",
      base: "Sandalwood, Musk",
    },
  },
  {
    id: "1002847263",
    image: testPerfume,
    name: "Amber Whisper",
    flavour: "Woody & Warm",
    price: "42500",
    description:
      "An intimate amber scent for cozy evenings and elegant nights.",
    inStock: true,
    category: "Amber",
    size: "100ml",
    notes: {
      top: "Mandarin, Pink Pepper",
      heart: "Amber, Patchouli",
      base: "Tonka Bean, Vanilla",
    },
  },
  {
    id: "1003948562",
    image: testPerfume,
    name: "Citrus Sky",
    flavour: "Fresh & Fruity",
    price: "29000",
    description: "A refreshing blend of citrus notes perfect for warm days.",
    inStock: false,
    category: "Citrus",
    size: "50ml",
    notes: {
      top: "Grapefruit, Lemon Zest",
      heart: "Jasmine, Orange Blossom",
      base: "Cedarwood, Musk",
    },
  },
  {
    id: "1004039583",
    image: testPerfume,
    name: "Velvet Oud",
    flavour: "Bold & Spicy",
    price: "55000",
    description:
      "A deep and luxurious oud with oriental spices and soft woods.",
    inStock: true,
    category: "Oriental",
    size: "100ml",
    notes: {
      top: "Saffron, Cinnamon",
      heart: "Oud, Rose",
      base: "Leather, Incense",
    },
  },
  {
    id: "1005894732",
    image: testPerfume,
    name: "Lilac Mist",
    flavour: "Floral & Soft",
    price: "33000",
    description: "Delicate lilac petals enveloped in a mist of morning dew.",
    inStock: true,
    category: "Floral",
    size: "75ml",
    notes: {
      top: "Lavender, Pear",
      heart: "Lilac, Rose",
      base: "White Musk, Amber",
    },
  },
  {
    id: "1006239573",
    image: testPerfume,
    name: "Royal Musk",
    flavour: "Earthy & Strong",
    price: "45000",
    description: "A royal blend of musky tones with hints of incense and wood.",
    inStock: false,
    category: "Musk",
    size: "100ml",
    notes: {
      top: "Incense, Bergamot",
      heart: "Musk, Jasmine",
      base: "Vetiver, Oakmoss",
    },
  },
  {
    id: "1007382649",
    image: testPerfume,
    name: "Sunset Bloom",
    flavour: "Sweet & Calm",
    price: "38000",
    description:
      "Gentle florals and warm vanilla to ease into dusk’s golden hour.",
    inStock: true,
    category: "Floral-Gourmand",
    size: "50ml",
    notes: {
      top: "Peach, Neroli",
      heart: "Magnolia, Iris",
      base: "Vanilla, Musk",
    },
  },
  {
    id: "1008429350",
    image: testPerfume,
    name: "Ocean Drift",
    flavour: "Aqua & Crisp",
    price: "30500",
    description: "Clean and crisp aquatic notes that evoke seaside serenity.",
    inStock: true,
    category: "Aquatic",
    size: "100ml",
    notes: {
      top: "Sea Breeze, Lemon",
      heart: "Water Lily, Violet",
      base: "Driftwood, Ambergris",
    },
  },
  {
    id: "1009547382",
    image: testPerfume,
    name: "Spice Trail",
    flavour: "Warm & Bold",
    price: "47000",
    description: "A spicy aromatic journey inspired by exotic trade routes.",
    inStock: false,
    category: "Spicy",
    size: "75ml",
    notes: {
      top: "Cardamom, Clove",
      heart: "Sandalwood, Nutmeg",
      base: "Amber, Tobacco",
    },
  },
  {
    id: "1010648392",
    image: testPerfume,
    name: "Midnight Rose",
    flavour: "Sensual & Elegant",
    price: "50000",
    description: "A mysterious rose bouquet wrapped in velvet nightfall.",
    inStock: true,
    category: "Floral",
    size: "100ml",
    notes: {
      top: "Blackcurrant, Rose",
      heart: "Jasmine, Violet",
      base: "Vanilla, Cashmere Wood",
    },
  },
  {
    id: "1011749382",
    image: testPerfume,
    name: "Pearl Dust",
    flavour: "Powdery & Soft",
    price: "36000",
    description: "Soft powdered elegance with a whisper of white florals.",
    inStock: true,
    category: "Powdery",
    size: "50ml",
    notes: {
      top: "Iris, Aldehydes",
      heart: "Honeysuckle, Heliotrope",
      base: "Musk, White Amber",
    },
  },
  {
    id: "1012850392",
    image: testPerfume,
    name: "Cedar Breeze",
    flavour: "Fresh & Woody",
    price: "41000",
    description: "A cool woody breeze through ancient cedar forests.",
    inStock: true,
    category: "Woody",
    size: "100ml",
    notes: {
      top: "Juniper, Bergamot",
      heart: "Cedar, Pine",
      base: "Vetiver, Moss",
    },
  },
  {
    id: "1013942382",
    image: testPerfume,
    name: "Orchid Noir",
    flavour: "Floral & Mysterious",
    price: "48500",
    description: "Dark orchid blooms with a heart of forbidden sweetness.",
    inStock: true,
    category: "Oriental-Floral",
    size: "100ml",
    notes: {
      top: "Plum, Black Orchid",
      heart: "Tuberose, Rose",
      base: "Patchouli, Myrrh",
    },
  },
  {
    id: "1015052392",
    image: testPerfume,
    name: "Desert Amber",
    flavour: "Resinous & Rich",
    price: "53000",
    description: "Rich, resinous warmth inspired by desert sands at dusk.",
    inStock: false,
    category: "Amber",
    size: "100ml",
    notes: {
      top: "Labdanum, Dried Fruit",
      heart: "Amber, Cinnamon",
      base: "Myrrh, Benzoin",
    },
  },
  {
    id: "1016153402",
    image: testPerfume,
    name: "White Sandal",
    flavour: "Clean & Woody",
    price: "39000",
    description: "A soft sandalwood base layered with clean, comforting notes.",
    inStock: true,
    category: "Woody",
    size: "75ml",
    notes: {
      top: "Lemon, Neroli",
      heart: "Sandalwood, Iris",
      base: "Musk, Cedar",
    },
  },
  {
    id: "2024000010",
    image: testPerfume,
    name: "Golden Dusk",
    flavour: "Oriental & Rich",
    price: "60000",
    description: "A golden hour fragrance full of warm resin and spice.",
    inStock: true,
    category: "Amber-Oriental",
    size: "100ml",
    notes: {
      top: "Saffron, Orange",
      heart: "Amber, Cinnamon",
      base: "Vanilla, Oud",
    },
  },
  {
    id: "2024000020",
    image: testPerfume,
    name: "Lavender Fields",
    flavour: "Calm & Refreshing",
    price: "32500",
    description: "Tranquil French lavender surrounded by soft citrus accents.",
    inStock: true,
    category: "Aromatic",
    size: "100ml",
    notes: {
      top: "Lavender, Lemon",
      heart: "Sage, Geranium",
      base: "Tonka, Musk",
    },
  },
  {
    id: "2024000030",
    image: testPerfume,
    name: "Silken Spice",
    flavour: "Warm & Inviting",
    price: "45000",
    description: "A silky fusion of warm spices and delicate woods.",
    inStock: true,
    category: "Spicy-Woody",
    size: "100ml",
    notes: {
      top: "Nutmeg, Cardamom",
      heart: "Rose, Cinnamon",
      base: "Sandalwood, Amber",
    },
  },
  {
    id: "2024000040",
    image: testPerfume,
    name: "Moonlit Garden",
    flavour: "Mystic & Floral",
    price: "58000",
    description: "Enchanted florals blooming under the silver moon.",
    inStock: false,
    category: "Floral",
    size: "75ml",
    notes: {
      top: "Gardenia, Night Jasmine",
      heart: "Orchid, Tuberose",
      base: "Cashmere Wood, Musk",
    },
  },
];

export const featuredPerfumes = [
  {
    id: "2024000010",
    image: testPerfume,
    name: "Golden Dusk",
    flavour: "Oriental & Rich",
    price: "60000",
    description: "A golden hour fragrance full of warm resin and spice.",
    inStock: true,
    category: "Amber-Oriental",
    size: "100ml",
    notes: {
      top: "Saffron, Orange",
      heart: "Amber, Cinnamon",
      base: "Vanilla, Oud",
    },
  },
  {
    id: "2024000020",
    image: testPerfume,
    name: "Lavender Fields",
    flavour: "Calm & Refreshing",
    price: "32500",
    description: "Tranquil French lavender surrounded by soft citrus accents.",
    inStock: true,
    category: "Aromatic",
    size: "100ml",
    notes: {
      top: "Lavender, Lemon",
      heart: "Sage, Geranium",
      base: "Tonka, Musk",
    },
  },
  {
    id: "2024000030",
    image: testPerfume,
    name: "Silken Spice",
    flavour: "Warm & Inviting",
    price: "45000",
    description: "A silky fusion of warm spices and delicate woods.",
    inStock: true,
    category: "Spicy-Woody",
    size: "100ml",
    notes: {
      top: "Nutmeg, Cardamom",
      heart: "Rose, Cinnamon",
      base: "Sandalwood, Amber",
    },
  },
  {
    id: "2024000040",
    image: testPerfume,
    name: "Moonlit Garden",
    flavour: "Mystic & Floral",
    price: "58000",
    description: "Enchanted florals blooming under the silver moon.",
    inStock: false,
    category: "Floral",
    size: "75ml",
    notes: {
      top: "Gardenia, Night Jasmine",
      heart: "Orchid, Tuberose",
      base: "Cashmere Wood, Musk",
    },
  },
];

export const images = {
  testPerfume,
};
