import testPerfume from "../assets/images/perfumes/parfum.webp";
import testPerfume2 from "../assets/images/perfumes/parfum.jpg";

export const perfumes = [
  {
    id: '1001827364',
    image: testPerfume,
    name: 'Meadow Bliss',
    flavour: 'Breezy & Joyful',
    price: '35000',
    description:
      'A light, airy fragrance evoking sun-drenched fields and carefree joy.',
    inStock: true,
    category: 'Floral',
    size: '100ml',
    notes: {
      top: 'Green Apple, Bergamot',
      heart: 'Peony, Freesia',
      base: 'Sandalwood, Musk',
    },
  },
  {
    id: '1002847263',
    image: testPerfume2,
    name: 'Amber Whisper',
    flavour: 'Woody & Warm',
    price: '42500',
    description:
      'An intimate amber scent for cozy evenings and elegant nights.',
    inStock: true,
    category: 'Amber',
    size: '100ml',
    notes: {
      top: 'Mandarin, Pink Pepper',
      heart: 'Amber, Patchouli',
      base: 'Tonka Bean, Vanilla',
    },
  },
  {
    id: '1003948562',
    image: testPerfume,
    name: 'Citrus Sky',
    flavour: 'Fresh & Fruity',
    price: '29000',
    description: 'A refreshing blend of citrus notes perfect for warm days.',
    inStock: false,
    category: 'Citrus',
    size: '50ml',
    notes: {
      top: 'Grapefruit, Lemon Zest',
      heart: 'Jasmine, Orange Blossom',
      base: 'Cedarwood, Musk',
    },
  },
  {
    id: '1004039583',
    image: testPerfume2,
    name: 'Velvet Oud',
    flavour: 'Bold & Spicy',
    price: '55000',
    description:
      'A deep and luxurious oud with oriental spices and soft woods.',
    inStock: true,
    category: 'Oriental',
    size: '100ml',
    notes: {
      top: 'Saffron, Cinnamon',
      heart: 'Oud, Rose',
      base: 'Leather, Incense',
    },
  },
  {
    id: '1005894732',
    image: testPerfume,
    name: 'Lilac Mist',
    flavour: 'Floral & Soft',
    price: '33000',
    description: 'Delicate lilac petals enveloped in a mist of morning dew.',
    inStock: true,
    category: 'Floral',
    size: '75ml',
    notes: {
      top: 'Lavender, Pear',
      heart: 'Lilac, Rose',
      base: 'White Musk, Amber',
    },
  },
  {
    id: '1006239573',
    image: testPerfume2,
    name: 'Royal Musk',
    flavour: 'Earthy & Strong',
    price: '45000',
    description: 'A royal blend of musky tones with hints of incense and wood.',
    inStock: false,
    category: 'Musk',
    size: '100ml',
    notes: {
      top: 'Incense, Bergamot',
      heart: 'Musk, Jasmine',
      base: 'Vetiver, Oakmoss',
    },
  },

  // FEMALE
  {
    id: '2001837465',
    image: testPerfume, // replace with your image
    name: 'Chanel No. 5',
    flavour: 'Floral & Powdery',
    price: '82000',
    description:
      "The most iconic women's fragrance, blending aldehydes with classic florals for timeless elegance.",
    inStock: true,
    category: 'Floral-Aldehyde',
    size: '100ml',
    gender: 'female',
    notes: {
      top: 'Aldehydes, Ylang-Ylang, Neroli',
      heart: 'Jasmine, Rose',
      base: 'Sandalwood, Vetiver, Vanilla',
    },
  },
  {
    id: '2002837466',
    image: testPerfume,
    name: "Dior J'adore",
    flavour: 'Fruity & Floral',
    price: '75000',
    description:
      'A luminous floral bouquet combining ylang-ylang, Damascus rose, and jasmine for a sensual feminine fragrance.',
    inStock: true,
    category: 'Floral',
    size: '100ml',
    gender: 'female',
    notes: {
      top: 'Pear, Melon, Magnolia',
      heart: 'Jasmine, Lily-of-the-Valley, Rose',
      base: 'Musk, Vanilla, Blackberry',
    },
  },
  {
    id: '2003837467',
    image: testPerfume,
    name: 'YSL Libre',
    flavour: 'Warm & Floral',
    price: '69000',
    description:
      'An iconic floral fragrance with lavender essence, orange blossom, and musk accord — bold and free.',
    inStock: true,
    category: 'Floral-Oriental',
    size: '90ml',
    gender: 'female',
    notes: {
      top: 'Lavender, Mandarin Orange, Black Currant',
      heart: 'Jasmine, Orange Blossom',
      base: 'Vanilla, Cedar, Musk',
    },
  },

  // MALE
  {
    id: '2004837468',
    image: testPerfume,
    name: 'Dior Sauvage',
    flavour: 'Fresh & Spicy',
    price: '68000',
    description:
      'Raw and noble — a fresh composition with Calabrian bergamot, Sichuan pepper, and ambroxan.',
    inStock: true,
    category: 'Aromatic-Fougere',
    size: '100ml',
    gender: 'male',
    notes: {
      top: 'Calabrian Bergamot, Pepper',
      heart: 'Lavender, Pink Pepper, Geranium',
      base: 'Ambroxan, Cedar, Labdanum',
    },
  },
  {
    id: '2005837469',
    image: testPerfume,
    name: 'Creed Aventus',
    flavour: 'F1',
    price: '150000',
    description:
      'Celebrated fragrance with a bold mix of pineapple, birch, and oak moss — a modern classic for men.',
    inStock: true,
    category: 'Chypre-Fruity',
    size: '100ml',
    gender: 'male',
    notes: {
      top: 'Pineapple, Blackcurrant, Apple, Bergamot',
      heart: 'Birch, Patchouli, Jasmine',
      base: 'Oak Moss, Ambergris, Vanilla',
    },
  },
  {
    id: '2006837470',
    image: testPerfume,
    name: 'Bleu de Chanel',
    flavour: 'Woody & Aromatic',
    price: '79000',
    description:
      'A sophisticated men’s fragrance combining citrus freshness with woods and amber for magnetic appeal.',
    inStock: true,
    category: 'Woody-Aromatic',
    size: '100ml',
    gender: 'male',
    notes: {
      top: 'Lemon, Mint, Pink Pepper',
      heart: 'Grapefruit, Ginger, Iso E Super',
      base: 'Sandalwood, Cedar, Amber, Patchouli',
    },
  },
  {
    id: '1007382649',
    image: testPerfume,
    name: 'Sunset Bloom',
    flavour: 'Sweet & Calm',
    price: '38000',
    description:
      'Gentle florals and warm vanilla to ease into dusk’s golden hour.',
    inStock: true,
    category: 'Floral-Gourmand',
    size: '50ml',
    notes: {
      top: 'Peach, Neroli',
      heart: 'Magnolia, Iris',
      base: 'Vanilla, Musk',
    },
  },
  {
    id: '1008429350',
    image: testPerfume2,
    name: 'Ocean Drift',
    flavour: 'Aqua & Crisp',
    price: '30500',
    description: 'Clean and crisp aquatic notes that evoke seaside serenity.',
    inStock: true,
    category: 'Aquatic',
    size: '100ml',
    notes: {
      top: 'Sea Breeze, Lemon',
      heart: 'Water Lily, Violet',
      base: 'Driftwood, Ambergris',
    },
  },
  {
    id: '1009547382',
    image: testPerfume,
    name: 'Spice Trail',
    flavour: 'Warm & Bold',
    price: '47000',
    description: 'A spicy aromatic journey inspired by exotic trade routes.',
    inStock: false,
    category: 'Spicy',
    size: '75ml',
    notes: {
      top: 'Cardamom, Clove',
      heart: 'Sandalwood, Nutmeg',
      base: 'Amber, Tobacco',
    },
  },
  {
    id: '1010648392',
    image: testPerfume2,
    name: 'Midnight Rose',
    flavour: 'Sensual & Elegant',
    price: '50000',
    description: 'A mysterious rose bouquet wrapped in velvet nightfall.',
    inStock: true,
    category: 'Floral',
    size: '100ml',
    notes: {
      top: 'Blackcurrant, Rose',
      heart: 'Jasmine, Violet',
      base: 'Vanilla, Cashmere Wood',
    },
  },
  {
    id: '1011749382',
    image: testPerfume,
    name: 'Pearl Dust',
    flavour: 'Powdery & Soft',
    price: '36000',
    description: 'Soft powdered elegance with a whisper of white florals.',
    inStock: true,
    category: 'Powdery',
    size: '50ml',
    notes: {
      top: 'Iris, Aldehydes',
      heart: 'Honeysuckle, Heliotrope',
      base: 'Musk, White Amber',
    },
  },
  {
    id: '1012850392',
    image: testPerfume2,
    name: 'Cedar Breeze',
    flavour: 'Fresh & Woody',
    price: '41000',
    description: 'A cool woody breeze through ancient cedar forests.',
    inStock: true,
    category: 'Woody',
    size: '100ml',
    notes: {
      top: 'Juniper, Bergamot',
      heart: 'Cedar, Pine',
      base: 'Vetiver, Moss',
    },
  },
  {
    id: '1013942382',
    image: testPerfume,
    name: 'Orchid Noir',
    flavour: 'Floral & Mysterious',
    price: '48500',
    description: 'Dark orchid blooms with a heart of forbidden sweetness.',
    inStock: true,
    category: 'Oriental-Floral',
    size: '100ml',
    notes: {
      top: 'Plum, Black Orchid',
      heart: 'Tuberose, Rose',
      base: 'Patchouli, Myrrh',
    },
  },
  {
    id: '1015052392',
    image: testPerfume2,
    name: 'Desert Amber',
    flavour: 'Resinous & Rich',
    price: '53000',
    description: 'Rich, resinous warmth inspired by desert sands at dusk.',
    inStock: false,
    category: 'Amber',
    size: '100ml',
    notes: {
      top: 'Labdanum, Dried Fruit',
      heart: 'Amber, Cinnamon',
      base: 'Myrrh, Benzoin',
    },
  },
  {
    id: '1016153402',
    image: testPerfume,
    name: 'White Sandal',
    flavour: 'Clean & Woody',
    price: '39000',
    description: 'A soft sandalwood base layered with clean, comforting notes.',
    inStock: true,
    category: 'Woody',
    size: '75ml',
    notes: {
      top: 'Lemon, Neroli',
      heart: 'Sandalwood, Iris',
      base: 'Musk, Cedar',
    },
  },
  {
    id: '2024000010',
    image: testPerfume2,
    name: 'Golden Dusk',
    flavour: 'Oriental & Rich',
    price: '60000',
    description: 'A golden hour fragrance full of warm resin and spice.',
    inStock: true,
    category: 'Amber-Oriental',
    size: '100ml',
    notes: {
      top: 'Saffron, Orange',
      heart: 'Amber, Cinnamon',
      base: 'Vanilla, Oud',
    },
  },
  {
    id: '2024000020',
    image: testPerfume,
    name: 'Lavender Fields',
    flavour: 'Calm & Refreshing',
    price: '32500',
    description: 'Tranquil French lavender surrounded by soft citrus accents.',
    inStock: true,
    category: 'Aromatic',
    size: '100ml',
    notes: {
      top: 'Lavender, Lemon',
      heart: 'Sage, Geranium',
      base: 'Tonka, Musk',
    },
  },
  {
    id: '2024000030',
    image: testPerfume2,
    name: 'Silken Spice',
    flavour: 'Warm & Inviting',
    price: '45000',
    description: 'A silky fusion of warm spices and delicate woods.',
    inStock: true,
    category: 'Spicy-Woody',
    size: '100ml',
    notes: {
      top: 'Nutmeg, Cardamom',
      heart: 'Rose, Cinnamon',
      base: 'Sandalwood, Amber',
    },
  },
  {
    id: '2024000040',
    image: testPerfume,
    name: 'Moonlit Garden',
    flavour: 'Mystic & Floral',
    price: '58000',
    description: 'Enchanted florals blooming under the silver moon.',
    inStock: false,
    category: 'Floral',
    size: '75ml',
    notes: {
      top: 'Gardenia, Night Jasmine',
      heart: 'Orchid, Tuberose',
      base: 'Cashmere Wood, Musk',
    },
  },
];

export const featuredPerfumes = [
  {
    id: "2024000010",
    image: testPerfume2,
    name: "Golden Dusk",
    flavour: "Oriental & Rich",
    price: "60000",
    description: "A golden hour fragrance full of warm resin and spice.",
    inStock: true,
    category: "Amber-Oriental",
    size: "100ml",
    notes: {
      top: "Saffron, Orange",
      heart: "Amber, Cinnamon",
      base: "Vanilla, Oud",
    },
  },
  {
    id: "2024000020",
    image: testPerfume,
    name: "Lavender Fields",
    flavour: "Calm & Refreshing",
    price: "32500",
    description: "Tranquil French lavender surrounded by soft citrus accents.",
    inStock: true,
    category: "Aromatic",
    size: "100ml",
    notes: {
      top: "Lavender, Lemon",
      heart: "Sage, Geranium",
      base: "Tonka, Musk",
    },
  },
  {
    id: "2024000030",
    image: testPerfume2,
    name: "Silken Spice",
    flavour: "Warm & Inviting",
    price: "45000",
    description: "A silky fusion of warm spices and delicate woods.",
    inStock: true,
    category: "Spicy-Woody",
    size: "100ml",
    notes: {
      top: "Nutmeg, Cardamom",
      heart: "Rose, Cinnamon",
      base: "Sandalwood, Amber",
    },
  },
  {
    id: "2024000040",
    image: testPerfume,
    name: "Moonlit Garden",
    flavour: "Mystic & Floral",
    price: "58000",
    description: "Enchanted florals blooming under the silver moon.",
    inStock: false,
    category: "Floral",
    size: "75ml",
    notes: {
      top: "Gardenia, Night Jasmine",
      heart: "Orchid, Tuberose",
      base: "Cashmere Wood, Musk",
    },
  },
];

export const newArrivals = [
  {
    id: "2024000010",
    image: testPerfume2,
    name: "Golden Dusk",
    flavour: "Oriental & Rich",
    price: "60000",
    description: "A golden hour fragrance full of warm resin and spice.",
    inStock: true,
    category: "Amber-Oriental",
    size: "100ml",
    notes: {
      top: "Saffron, Orange",
      heart: "Amber, Cinnamon",
      base: "Vanilla, Oud",
    },
  },
  {
    id: "2024000020",
    image: testPerfume,
    name: "Lavender Fields",
    flavour: "Calm & Refreshing",
    price: "32500",
    description: "Tranquil French lavender surrounded by soft citrus accents.",
    inStock: true,
    category: "Aromatic",
    size: "100ml",
    notes: {
      top: "Lavender, Lemon",
      heart: "Sage, Geranium",
      base: "Tonka, Musk",
    },
  },
  {
    id: "2024000030",
    image: testPerfume2,
    name: "Silken Spice",
    flavour: "Warm & Inviting",
    price: "45000",
    description: "A silky fusion of warm spices and delicate woods.",
    inStock: true,
    category: "Spicy-Woody",
    size: "100ml",
    notes: {
      top: "Nutmeg, Cardamom",
      heart: "Rose, Cinnamon",
      base: "Sandalwood, Amber",
    },
  },
];
export const images = {
  testPerfume,
  testPerfume2,
};
